pipeline:
  name: "Default Text Embedding Pipeline"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

data:
  text_column: "text"
  id_column: "id"
  # Optional: sampling parameters (can be overridden by CLI flags)
  # sample_size: 10000  # Maximum number of samples to use
  # sample_seed: 42     # Random seed for reproducibility
  outcomes:
    - name: "outcome1"
      display_name: "Outcome 1"
      type: "continuous"
      range: [0, 100]
      default_thresholds:
        low_percentile: 25
        high_percentile: 75
    
    - name: "outcome2"
      display_name: "Outcome 2"
      type: "continuous"
      range: [1, 10]
      default_thresholds:
        low_percentile: 25
        high_percentile: 75

analysis:
  pca_components: 100
  umap_dimensions: 3
  umap_n_neighbors: 15
  umap_min_dist: 0.1
  hdbscan_min_cluster_size: 30
  hdbscan_min_samples: 5
  dml_top_pcs: null  # Auto-select
  dml_n_folds: 5
  xgb_n_estimators: 100
  xgb_max_depth: 5
  batch_size: 32
  max_text_length: 512

visualization:
  title: "Text Embedding Analysis"
  point_size: 4.0
  default_opacity: 0.8
  essay_font_size: 24
  auto_rotate_speed: 2
  transition_speed: 0.2
  topic_text_size: 15
  topic_opacity: 0.7

output_dir: "./output"
checkpoint_dir: "./checkpoints"